// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "BoxHandler.h"
#include "../RobotMap.h"
#include "../Robot.h"
#include "SmartDashboard/SmartDashboard.h"
#include "../Commands/BoxHandlerTrigger.h"
#include "../Commands/IntakeBox.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

BoxHandler::BoxHandler() : frc::Subsystem("BoxHandler") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    boxDetect = RobotMap::boxHandlerBoxDetect;
    leftArmWheel = RobotMap::boxHandlerLeftArmWheel;
    rightArmWheel = RobotMap::boxHandlerRightArmWheel;
    solenoid = RobotMap::boxHandlerSolenoid;
    boxGrabber = RobotMap::boxHandlerGrabber;

    if (Robot::isTesting){
    	frc::SmartDashboard::PutBoolean("boxDetect", false);
    	frc::SmartDashboard::PutBoolean("boxPutter", false);
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void BoxHandler::InitDefaultCommand() {
	//SetDefaultCommand(new BoxHandlerTrigger());
	SetDefaultCommand(new IntakeBox(0.2));
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void BoxHandler::Periodic() {
    // Put code here to be run every loop

}

void BoxHandler::setLeftSpeed(double speed) {
	leftArmWheel->Set(speed);
}
void BoxHandler::setRightSpeed(double speed) {
	rightArmWheel->Set(-speed);
}
bool BoxHandler::getLimitSwitch() {
	if(Robot::isTesting){
		return frc::SmartDashboard::GetBoolean("boxDetect", false);
	}
	else{
		frc::SmartDashboard::PutBoolean("boxDetect", !boxDetect->Get());
		return !boxDetect->Get();
	}
}
double BoxHandler::getLeftSpeed() {
	if(Robot::isTesting){
		return frc::SmartDashboard::GetNumber("leftArmWheel", -999);
		}
	else{
		return leftArmWheel->Get();
	}
}
double BoxHandler::getRightSpeed() {
	if(Robot::isTesting){
		return frc::SmartDashboard::GetNumber("rightArmWheel", -999);
	}
	else{
		return rightArmWheel->Get();
	}
}
bool BoxHandler::getPiston(){
	if(Robot::isTesting){
		return frc::SmartDashboard::GetNumber("solenoid", false);
	}
	else{
		return solenoid->Get();
	}
}
void BoxHandler::setPiston(bool state){
	solenoid->Set(state);
	frc::SmartDashboard::PutBoolean("boxPutter", state);
}

void BoxHandler::closeGrabber(bool state){
	//boxGrabber->Set(state);
	frc::SmartDashboard::PutBoolean("boxGrabber", state);
}

bool BoxHandler::getGrabber(){
	if(Robot::isTesting) {
		return frc::SmartDashboard::GetNumber("solenoid", false);
	}
	else{
		return solenoid->Get();
	}
}



// Put methods for controlling this subsystem
// here. Call these from Commands.

