// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveStraightDistance.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveStraightDistance::DriveStraightDistance(double distance, double rate): frc::Command() {
    m_distance = distance;
    m_rate = rate;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveStraightDistance::Initialize() {
	Robot::driveTrain->ArcadeDrive(m_rate, 0);
	Robot::driveTrain->resetDistanceCounter();
}

// Called repeatedly when this Command is scheduled to run
void DriveStraightDistance::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool DriveStraightDistance::IsFinished() {
    if(abs(Robot::driveTrain->getRightDistanceCounter()) < m_distance) return false;
    else return true;
}

// Called once after isFinished returns true
void DriveStraightDistance::End() {
	Robot::driveTrain->ArcadeDrive(0, 0);
	Robot::driveTrain->resetDistanceCounter();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveStraightDistance::Interrupted() {
	Robot::driveTrain->ArcadeDrive(0, 0);
	Robot::driveTrain->resetDistanceCounter();
}
