// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "IntakeBox.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeBox::IntakeBox(double rate): frc::Command() {
    m_rate = rate;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::boxHandler.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void IntakeBox::Initialize() {
	Robot::boxHandler->setLeftSpeed(1 * m_rate);
	Robot::boxHandler->setRightSpeed(1 * m_rate);
}

// Called repeatedly when this Command is scheduled to run
void IntakeBox::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeBox::IsFinished() {
	if(Robot::boxHandler->getLimitSwitch()) {
		return false;
	}
	else return true;
}

// Called once after isFinished returns true
void IntakeBox::End() {
	Robot::boxHandler->setLeftSpeed(0);
	Robot::boxHandler->setRightSpeed(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeBox::Interrupted() {
	Robot::boxHandler->setLeftSpeed(0);
	Robot::boxHandler->setRightSpeed(0);
}
