// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "TurnNoGyro.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TurnNoGyro::TurnNoGyro(double angle, double rate): frc::Command() {
    m_angle = angle;
    m_rate = rate;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void TurnNoGyro::Initialize() {
	arc = (m_angle / 360) * 11.75 * 2 *  PI;
}

// Called repeatedly when this Command is scheduled to run
void TurnNoGyro::Execute() {
	if(m_angle > 0 && Robot::driveTrain->getRightDistanceCounter() + Robot::driveTrain->getRightDistanceCounter() / 2 < arc) {
		Robot::driveTrain->TankDrive(-m_rate , m_rate);
	}
	if(m_angle < 0 && Robot::driveTrain->getRightDistanceCounter() + Robot::driveTrain->getRightDistanceCounter() / 2 < arc) {
			Robot::driveTrain->TankDrive(m_rate , -m_rate);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool TurnNoGyro::IsFinished() {
	return Robot::driveTrain->getRightDistanceCounter() + Robot::driveTrain->getRightDistanceCounter() / 2 <= arc;
}

// Called once after isFinished returns true
void TurnNoGyro::End() {
	Robot::driveTrain->TankDrive(0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnNoGyro::Interrupted() {
	Robot::driveTrain->TankDrive(0 , 0);
}
