// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/CenterAuto.h"
#include "Commands/DeployBJoings.h"
#include "Commands/DeployLeftWing.h"
#include "Commands/DeployRightWing.h"
#include "Commands/DisengagePTO.h"
#include "Commands/DriveStraightDistance.h"
#include "Commands/DriveStraightTimed.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/EjectBox.h"
#include "Commands/EngageHighGear.h"
#include "Commands/EngagePTO.h"
#include "Commands/IntakeBox.h"
#include "Commands/LeftAuto.h"
#include "Commands/LiftToHeight.h"
#include "Commands/LiftWithJoystick.h"
#include "Commands/ResetGyro.h"
#include "Commands/RetractBJoings.h"
#include "Commands/RightAuto.h"
#include "Commands/SampleAutonomousCommand.h"
#include "Commands/StartCompressor.h"
#include "Commands/StopCompressor.h"
#include "Commands/TurnAngle.h"
#include "Commands/TurnTimed.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick.reset(new frc::Joystick(0));
    
    startButton.reset(new frc::JoystickButton(joystick.get(), 8));
    startButton->WhileHeld(new EngagePTO());
    selectButton.reset(new frc::JoystickButton(joystick.get(), 7));
    selectButton->WhileHeld(new DeployBJoings());
    rightBumper.reset(new frc::JoystickButton(joystick.get(), 6));
    rightBumper->WhileHeld(new DeployRightWing());
    leftBumper.reset(new frc::JoystickButton(joystick.get(), 5));
    leftBumper->WhileHeld(new DeployLeftWing());
    yButton.reset(new frc::JoystickButton(joystick.get(), 4));
    yButton->WhileHeld(new LiftToHeight(40));
    xButton.reset(new frc::JoystickButton(joystick.get(), 3));
    xButton->WhileHeld(new LiftToHeight(0));
    bButton.reset(new frc::JoystickButton(joystick.get(), 2));
    bButton->WhileHeld(new EjectBox(0.5));
    aButton.reset(new frc::JoystickButton(joystick.get(), 1));
    aButton->WhileHeld(new IntakeBox(0.5));

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("RetractBJoings", new RetractBJoings());
    frc::SmartDashboard::PutData("ResetGyro", new ResetGyro());
    frc::SmartDashboard::PutData("StopCompressor", new StopCompressor());
    frc::SmartDashboard::PutData("StartCompressor", new StartCompressor());
    frc::SmartDashboard::PutData("DisengagePTO", new DisengagePTO());
    frc::SmartDashboard::PutData("EngagePTO", new EngagePTO());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystick() {
   return joystick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
