// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "Triggers/LeftTrigger2.h"
#include "Triggers/RightTrigger2.h"


class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	std::shared_ptr<frc::Joystick> joystick;
	std::shared_ptr<frc::JoystickButton> selectButton;
	std::shared_ptr<frc::JoystickButton> rightBumper;
	std::shared_ptr<frc::JoystickButton> leftBumper;
	std::shared_ptr<frc::JoystickButton> yButton;
	std::shared_ptr<frc::JoystickButton> xButton;
	std::shared_ptr<frc::JoystickButton> bButton;
	std::shared_ptr<frc::JoystickButton> aButton;
	std::shared_ptr<frc::JoystickButton> startButton;

	std::shared_ptr<frc::Joystick> joystick2;
	std::shared_ptr<frc::JoystickButton> selectButton2;
	std::shared_ptr<frc::JoystickButton> rightBumper2;
	std::shared_ptr<frc::JoystickButton> leftBumper2;
	std::shared_ptr<frc::JoystickButton> yButton2;
	std::shared_ptr<frc::JoystickButton> xButton2;
	std::shared_ptr<frc::JoystickButton> bButton2;
	std::shared_ptr<frc::JoystickButton> aButton2;
	std::shared_ptr<frc::JoystickButton> startButton2;
	std::shared_ptr<usr::LeftTrigger2> leftTrigger2;
	std::shared_ptr<usr::RightTrigger2> rightTrigger2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	std::shared_ptr<frc::Joystick> getJoystick();
	std::shared_ptr<frc::JoystickButton> leftJoystick;
	std::shared_ptr<frc::Joystick> getJoystick2();
		std::shared_ptr<frc::JoystickButton> leftJoystick2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
