// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES


#include "Commands/CenterAuto.h"
#include "Commands/SideAuto.h"
#include "Subsystems/JetsonVision.h"
#include "Subsystems/BoxHandler.h"
#include "Subsystems/DriveTrain.h"
#include "Subsystems/EndgameExtensions.h"
#include "Subsystems/Lift.h"
#include "Subsystems/Climber.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	//frc::SendableChooser<frc::Command*> chooser;
	frc::SendableChooser<int> targetChooser;
	frc::SendableChooser<std::string> locationChooser;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<DriveTrain> driveTrain;
	static std::shared_ptr<JetsonVision> jetsonVision;
	static std::shared_ptr<BoxHandler> boxHandler;
	static std::shared_ptr<Lift> lift;
	static std::shared_ptr<EndgameExtensions> endgameExtensions;
	static std::shared_ptr<frc::Timer> TimeTurner;
	static std::shared_ptr<Climber> climber;
	static std::string SwitchPosition;
	static std::string location;
	static int target;
	static bool isTesting;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;

};
#endif
